declare const MAGIC_LO = 1902200623;
declare const MAGIC_HI = 4224036245;
declare const MAGIC_PAYLOAD = 284243047;
declare const DEFAULT_STREAM_BODY_BUFFER_SIZE: number;
declare const icHeartBeat = -4;
declare const icEndSession = -5;
declare const icFlushQueue = -6;
declare const icUniqueClientID = -7;
declare const icTimeStamp = -8;
declare const icEvent = -15;
declare const icEndClientSession = -21;
declare const icFlushClientQueue = -22;
declare const icConnectToGateway = -23;
declare const icSetClientInfo = -31;
declare const icSetVariable = -32;
declare const icAllVariables = -33;
declare const icSetState = -34;
declare const icSetThrottle = -35;
declare const icSetNoDelay = -36;
declare const icSetVariablePrefixed = -37;
declare const icRequestEventNames = -41;
declare const icEventNames = -42;
declare const icRequestSubscribers = -43;
declare const icRequestPublishers = -44;
declare const icSubscribe = -45;
declare const icUnsubscribe = -46;
declare const icPublish = -47;
declare const icUnpublish = -48;
declare const icSetEventIDTranslation = -49;
declare const icStatusEvent = -52;
declare const icStatusClient = -53;
declare const icStatusEventPlus = -54;
declare const icStatusClientPlus = -55;
declare const icStatusHUB = -56;
declare const icStatusTimer = -57;
declare const icHumanReadableHeader = -60;
declare const icSetMonitor = -61;
declare const icResetMonitor = -62;
declare const icCreateTimer = -73;
declare const icHUBLocate = -81;
declare const icHUBFound = -82;
declare const icLogClear = -91;
declare const icLogRequest = -92;
declare const icLogContents = -93;
declare const actionNew = 0;
declare const actionDelete = 1;
declare const actionChange = 2;
declare const ekChangeObjectEvent = 0;
declare const ekStreamHeader = 1;
declare const ekStreamBody = 2;
declare const ekStreamTail = 3;
declare const ekBuffer = 4;
declare const ekNormalEvent = 5;
declare const ekChangeObjectDataEvent = 6;
declare const ekChildEventAdd = 11;
declare const ekChildEventRemove = 12;
declare const ekLogWriteLn = 30;
declare const ekTimerCancel = 40;
declare const ekTimerPrepare = 41;
declare const ekTimerStart = 42;
declare const ekTimerStop = 43;
declare const ekTimerAcknowledgedListAdd = 45;
declare const ekTimerAcknowledgedListRemove = 46;
declare const ekTimerSetSpeed = 47;
declare const ekTimerTick = 48;
declare const ekTimerAcknowledge = 49;
declare const ekTimerStatusRequest = 50;
declare function signalCommand(aSocket: any, aCommand: any, aPayload: any): void;
declare function signalSubscribe(aSocket: any, aEventID: any, aEventEntryType: any, aEventName: any): void;
declare function signalUnSubscribe(aSocket: any, aEventName: any): void;
declare function signalPublish(aSocket: any, aEventID: any, aEventEntryType: any, aEventName: any): void;
declare function signalUnPublish(aSocket: any, aEventName: any): void;
declare function signalClientInfo(aSocket: any, aOwnerID: any, aOwnerName: any): void;
declare function signalChangeObject(aSocket: any, aEventID: any, aAction: any, aObjectID: any, aAttribute: any): void;
declare function signalNormalEvent(aSocket: any, aEventID: any, aEventKind: any, aEventPayload: any): void;
declare function hashCode(s: any): any;
declare function signalStream(aSocket: any, aEventID: any, aStreamName: any, aStream: any): void;
