import { Request, Response, Express } from 'express';
import ApiManager = require('./ApiManager');
import BaseConnector = require('./BaseConnector');
export declare class RestAPI extends BaseConnector.BaseConnector {
    server: Express;
    baseUrl: string;
    manager: ApiManager.ApiManager;
    resourceUrl: any;
    layersUrl: any;
    keysUrl: any;
    filesUrl: any;
    searchUrl: any;
    projectsUrl: any;
    proxyUrl: any;
    tilesUrl: any;
    constructor(server: Express, baseUrl?: string);
    private getResources;
    private getTheResource;
    private createTheResource;
    private updateTheResource;
    private getLayers;
    private getTheProjects;
    private getTheProject;
    private updateTheProject;
    private createTheProject;
    private deleteTheProject;
    private addTheLayer;
    deleteTheLayer(req: Request, res: Response): void;
    private deleteTheLayer2;
    private getTheGroups;
    private createTheGroup;
    private updateTheGroup;
    private deleteTheGroup;
    private createTheLayer;
    /** Similar to createLayer, but also checks if a layer exists: Should probably be removed as it is an update! */
    private createTheLayer2;
    private getTheLayer;
    private updateTheLayer;
    private addTheFeature;
    private getTheFeature;
    private updateTheFeature;
    private deleteTheFeature;
    private searchLayers;
    private getLayerFeaturesInBBox;
    private getLayerFeaturesInSphere;
    private getLayerFeaturesInPolygon;
    private updateTheKey;
    private getTheKeys;
    private getTheKey;
    private addTheFile;
    private getTheFile;
    private addTheLogs;
    private addTheLog;
    private getTheLog;
    private deleteTheLog;
    private getLogs;
    private proxyTheUrl;
    init(layerManager: ApiManager.ApiManager, options: any, callback: Function): void;
    private getUrl;
    private cloneWithoutUnderscore;
}
